type fixed and improved
ItzDerock/discord-html-transcripts pull request #72
Opened 2022-09-25 18:10 UTC by imranbarbhuiya

Some typings were fixed and improved.
Exported enum so that users can use it
added a prettier config
changed the tsconfig

You can check commit wise to see all the changes one by one as all the commits has valid messages

2022-09-25 19:54 UTC, ItzDerock commented
I'm not a huge fan of the larger tab size, can you revert it back to 2 spaces?

2022-09-25 23:53 UTC, imranbarbhuiya commented
ig it's already in 2 spaces.

2022-09-26 00:29 UTC, ItzDerock commented
you've set it to use the actual tab character instead of two spaces, and in your vsc you probably have some sort of setting that renders the tab character as two spaces.

2022-09-26 17:33 UTC, ItzDerock requested changes

2022-09-26 17:33 UTC, ItzDerock commented on tsconfig.json
> +    "target": "esnext",
what versions of node support esnext target?

2022-09-26 18:34 UTC, imranbarbhuiya commented
@ItzDerock  applied all the suggestions. Review once more. This pr is complete. And after u merge https://github.com/ItzDerock/discord-markdown-parser/pull/3 and release, I'll add support for that in a new pr

2022-09-26 18:51 UTC, ItzDerock approved these changes
lgtm!

2022-09-26 18:52 UTC, ItzDerock approved these changes
oops, forgot some files in my last review
everything else looks good!

2022-09-26 18:54 UTC, ItzDerock commented
is there anything else you want to put in this pr, or is it ok to merge right now.

2022-09-26 18:55 UTC, imranbarbhuiya commented
yeah u can merge it now. I'll create another pr with support for twemoji once u release new version of `discord-markdown-parser`.

2022-09-26 19:21 UTC, merged